### ISSUE TITLE
Loader fails to load

### ISSUE THREAD

**Issue by jjpe** [ballercat/wasm-loader#12]
I've configured my webpack.config.js as follows, but running `npx webpack fails`:

``` javascript
module.exports = {
    entry: "./index.js",
    output: {
        path: path.resolve(__dirname, "dist"),
        filename: "bundle.js",
    },
    mode: "development",
    plugins: [
        new CopyWebpackPlugin([
            'pkg/README.md',
            'pkg/package-lock.json',
            'pkg/package.json',
            'pkg/sbr_validate_npm.d.ts',
            'pkg/sbr_validate_npm.js',
            'pkg/sbr_validate_npm_bg.d.ts',
            'pkg/sbr_validate_npm_bg.js',
            'pkg/sbr_validate_npm_bg.wasm',
        ])
    ],
    module: {
        rules: [
            { test: /\.wasm$/, use: [ { loader: 'wasm-loader' } ] }
        ]
    }
};
```

The error log is:
```
 ✘  ~/Development/accept/sbr-validate-npm   wasm ●  npx webpack
Hash: 131a21bb312c8396a99a
Version: webpack 4.27.1
Time: 3483ms
Built at: 12/06/2018 3:58:53 PM
                   Asset       Size  Chunks             Chunk Names
               README.md   1.22 KiB          [emitted]
               bundle.js   1.13 MiB    main  [emitted]  main
       package-lock.json   79 bytes          [emitted]
            package.json  534 bytes          [emitted]
   sbr_validate_npm.d.ts  217 bytes          [emitted]
     sbr_validate_npm.js   4.89 KiB          [emitted]
sbr_validate_npm_bg.d.ts  599 bytes          [emitted]
  sbr_validate_npm_bg.js  362 bytes          [emitted]
sbr_validate_npm_bg.wasm   3.76 MiB          [emitted]
Entrypoint main = bundle.js
[./index.js] 132 bytes {main} [built]
[./node_modules/moment/locale sync recursive ^\.\/.*$] ./node_modules/moment/locale sync ^\.\/.*$ 2.91 KiB {main} [optional] [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {main} [built]
[./pkg/sbr_validate_npm.js] 4.89 KiB {main} [built]
[./pkg/sbr_validate_npm_bg.wasm] 2.67 KiB {main} [built] [failed] [1 error]
[./src/franks_replacements.js] 7.08 KiB {main} [built]
    + 125 hidden modules

ERROR in ./pkg/sbr_validate_npm_bg.wasm
Module parse failed: magic header not detected
You may need an appropriate loader to handle this file type.
Error: magic header not detected
    at new CompileError (/Users/j/Development/accept/sbr-validate-npm/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
    at parseModuleHeader (/Users/j/Development/accept/sbr-validate-npm/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:287:13)
    at Object.decode (/Users/j/Development/accept/sbr-validate-npm/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1545:3)
    at decode (/Users/j/Development/accept/sbr-validate-npm/node_modules/@webassemblyjs/wasm-parser/lib/index.js:240:21)
    at WebAssemblyParser.parse (/Users/j/Development/accept/sbr-validate-npm/node_modules/webpack/lib/wasm/WebAssemblyParser.js:74:19)
    at doBuild.err (/Users/j/Development/accept/sbr-validate-npm/node_modules/webpack/lib/NormalModule.js:460:32)
    at runLoaders (/Users/j/Development/accept/sbr-validate-npm/node_modules/webpack/lib/NormalModule.js:342:12)
    at /Users/j/Development/accept/sbr-validate-npm/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/j/Development/accept/sbr-validate-npm/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/Users/j/Development/accept/sbr-validate-npm/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/j/Development/accept/sbr-validate-npm/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at Object.context.callback (/Users/j/Development/accept/sbr-validate-npm/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.module.exports (/Users/j/Development/accept/sbr-validate-npm/node_modules/wasm-loader/index.js:34:8)
    at LOADER_EXECUTION (/Users/j/Development/accept/sbr-validate-npm/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/j/Development/accept/sbr-validate-npm/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/j/Development/accept/sbr-validate-npm/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/j/Development/accept/sbr-validate-npm/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/j/Development/accept/sbr-validate-npm/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/j/Development/accept/sbr-validate-npm/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/j/Development/accept/sbr-validate-npm/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
 @ ./pkg/sbr_validate_npm.js 2:0-46 10:71-82 11:45-56 32:16-38 40:73-84 41:47-58 95:4-24 119:4-31 135:19-39 141:15-43 151:30-51 154:12-32 170:30-58 173:12-32 174:12-32 187:30-61 190:12-32
 @ ./index.js

ERROR in ./pkg/sbr_validate_npm_bg.wasm
WebAssembly module is included in initial chunk.
This is not allowed, because WebAssembly download and compilation must happen asynchronous.
Add an async splitpoint (i. e. import()) somewhere between your entrypoint and the WebAssembly module:
* ./index.js --> ./pkg/sbr_validate_npm.js --> ./pkg/sbr_validate_npm_bg.wasm
```

The error log says that WASM modules must be compiled asynchronously.
But if I need to do that, what's the point of `wasm-loader`?

**Comment by etisdew** [comment]
May I piggy back on this issue to check up with the library author to get a sense of where this moving target is currently (Wasm)? A lot happens in a couple months and a lot of work that made sense is ever increasingly expiring. I haven't had the chance to run this but am shopping for a commit-able build pipeline before I paint myself into a corner. It fits the bill for the strategy I would prefer to take, being able to bundle but as the poster stated this error indicates a conscious effort to steer the community in a direction without an obvious or clear communication of reasoning. Is this still going to be a valid strategy or have your efforts been steam rolled by browser implementation?

**Comment by xtuc** [comment]
Browser implementation has still some time to go but you can now use WebAssemblyjs natively in Webpack.

**Comment by Maswor** [comment]
I'm also having this problem with "magic header not detected". Anyone know how to get around it?

**Comment by ballercat** [comment]
Please use native Webpack 5 WebAssembly support. Here's a small demo: https://github.com/ballercat/minimal-webpack5-wasm-demo
