### ISSUE TITLE
Module parse failed: magic header not detected

### ISSUE THREAD

**Issue by weihualiu** [ballercat/wasm-loader#15]
node: v10.19.0
vue: @vue/cli 4.5.13
wasm-loader:  "version": "1.3.0"

vue.config.js
```json
const path = require("path");
const IS_PROD = ['production', 'prod'].includes(process.env.NODE_ENV);
const resolve = (dir) => path.join(__dirname, dir);
module.exports = {
    publicPath: process.env.NODE_ENV === 'production' ? '/site/vue-demo/' : '/',  
    indexPath: 'index.html' , 
    outputDir: process.env.outputDir || 'dist',
    assetsDir: 'static', 
    lintOnSave: false, 
    runtimeCompiler: true, 
    productionSourceMap: !IS_PROD, 
    parallel: require("os").cpus().length > 1, 
    pwa: {}, 
    chainWebpack: config => {
        config.resolve.symlinks(true); 
       
        config.plugin("html").tap(args => {
            
            args[0].chunksSortMode = "none";
            return args;
        });
        config.resolve.alias
            .set('@', resolve('src'))
            .set('@assets', resolve('src/assets'))
            .set('@components', resolve('src/components'))
            .set('@views', resolve('src/views'))
            .set('@store', resolve('src/store'));
        config.module
            .rule('wasm')
            .test(/\.wasm$/)
            .use('wasm-loader')
            .loader('wasm-loader')
            .end();
    },
    css: {
        extract: IS_PROD,
        requireModuleExtension: false,
        loaderOptions: {
             
                less: {
                    // `globalVars`
                    globalVars: {
                        primary: '#333'
                    }
                }
        }
    },
    devServer: {
            overlay: {
              warnings: true,
              errors: true
            },
            host: "localhost",
            port: 8080,
            https: false,
            open: false, 
            hotOnly: true, 
            // proxy: 'http://localhost:8080'
            proxy: {
                "/api": {
                    target: "http://172.11.11.11:7071",
                    changeOrigin: true,
                    // ws: true,//websocket
                    secure: false,
                    pathRewrite: {
                        "^/api": "/"
                    }
                },
                "/api2": {
                    target: "http://172.12.12.12:2018",
                    changeOrigin: true,
                    //ws: true,//websocket
                    secure: false,
                    pathRewrite: {
                        "^/api2": "/"
                    }
                },
            }
        }
}
````

App.vue:
```javascript
<template>
  <img alt="Vue logo" src="./assets/logo.png">
  <HelloWorld msg="Welcome to Your Vue.js App"/>
  <button @click="js_greet('hello world')">Greet me</button>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'

export default {
  name: 'App',
  components: {
    HelloWorld
  },
  methods: {
    async js_greet(message) {
      const wasm = import("../wasm/alert");
      const greet = (await wasm).greet;
      greet(message);
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

found error below:
```shell
Module parse failed: magic header not detected
File was processed with these loaders:
* ./node_modules/wasm-loader/index.js
You may need an additional loader to handle the result of these loaders.
Error: magic header not detected
at new CompileError (/home/dev/webassembly/webapp/demo_vue2/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
at parseModuleHeader (/home/dev/webassembly/webapp/demo_vue2/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:287:13)
at Object.decode (/home/dev/webassembly/webapp/demo_vue2/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1681:3)
at decode (/home/dev/webassembly/webapp/demo_vue2/node_modules/@webassemblyjs/wasm-parser/lib/index.js:248:21)
at WebAssemblyParser.parse (/home/dev/webassembly/webapp/demo_vue2/node_modules/webpack/lib/wasm/WebAssemblyParser.js:74:19)
at doBuild.err (/home/dev/webassembly/webapp/demo_vue2/node_modules/webpack/lib/NormalModule.js:482:32)
at runLoaders (/home/dev/webassembly/webapp/demo_vue2/node_modules/webpack/lib/NormalModule.js:358:12)
at /home/dev/webassembly/webapp/demo_vue2/node_modules/loader-runner/lib/LoaderRunner.js:373:3
at iterateNormalLoaders (/home/dev/webassembly/webapp/demo_vue2/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
at iterateNormalLoaders (/home/dev/webassembly/webapp/demo_vue2/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
at /home/dev/webassembly/webapp/demo_vue2/node_modules/loader-runner/lib/LoaderRunner.js:236:3
at Object.context.callback (/home/dev/webassembly/webapp/demo_vue2/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
at Object.module.exports (/home/dev/webassembly/webapp/demo_vue2/node_modules/wasm-loader/index.js:34:8)
at LOADER_EXECUTION (/home/dev/webassembly/webapp/demo_vue2/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
at runSyncOrAsync (/home/dev/webassembly/webapp/demo_vue2/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
at iterateNormalLoaders (/home/dev/webassembly/webapp/demo_vue2/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
@ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=js 5:0-53 23:27-32
@ ./src/App.vue?vue&type=script&lang=js
@ ./src/App.vue
@ ./src/main.js
@ multi (webpack)-dev-server/client?http://localhost:8080&sockPath=/sockjs-node (webpack)/hot/only-dev-server.js ./src/main.js
error in ./wasm/alert/wasm_alert_bg.wasm
```

**Comment by weihualiu** [comment]
https://github.com/ballercat/wasm-loader/blob/d4dbd36fdd6d4c39c3c11f7e5d9667d0d8e8631d/index.js#L34
change
```javascript
this.callback(null, out);
```
to
```javascirpt
this.callback(null, buffer);
```
the wasm-loader is working.

**Comment by ballercat** [comment]
After taking a look into this there is nothing to be fixed. The "solution" posted a while is just a misunderstanding(?) of what the loader is meant to do.

Performing this change `this.callback(null, buffer);` simply makes the the plugin not do anything (I'm ignoring the minor `wasmDCE`  feature) since that would return the original Buffer of the file being processed without any additional loading/transform.

I'm not familiar with vuejs myself but it seems that something is already attempting to load your `.wasm` files for you and it's complaining that it's basically no longer a buffer containing the binary data for the module but a JavaScript module instead. Note that `wasm -> JS module` is the primary job of this plugin, which was written for Webpack v3 support.

Remove the plugin and use whatever native support for `.wasm` files your build tool(s) provide, in this case Vuejs.
